#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: f4bef72
#
Name     : R-gamlss
Version  : 5.4.22
Release  : 17
URL      : https://cran.r-project.org/src/contrib/gamlss_5.4-22.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gamlss_5.4-22.tar.gz
Summary  : Generalized Additive Models for Location Scale and Shape
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-gamlss-lib = %{version}-%{release}
Requires: R-gamlss.data
Requires: R-gamlss.dist
BuildRequires : R-gamlss.data
BuildRequires : R-gamlss.dist
BuildRequires : buildreq-R

%description
# gamlss: Generalized Additive Models for Location Scale and Shape
Functions for fitting the Generalized Additive Models for Location Scale and Shape introduced by
[Rigby and Stasinopoulos (2005)](https://doi.org/10.1111/j.1467-9876.2005.00510.x).
The models use a distributional regression approach where all the parameters of the conditional
distribution of the response variable are modelled using explanatory variables.

%package lib
Summary: lib components for the R-gamlss package.
Group: Libraries

%description lib
lib components for the R-gamlss package.


%prep
%setup -q -n gamlss
pushd ..
cp -a gamlss buildavx2
popd
pushd ..
cp -a gamlss buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710949459

%install
export SOURCE_DATE_EPOCH=1710949459
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gamlss/CITATION
/usr/lib64/R/library/gamlss/DESCRIPTION
/usr/lib64/R/library/gamlss/INDEX
/usr/lib64/R/library/gamlss/Meta/Rd.rds
/usr/lib64/R/library/gamlss/Meta/features.rds
/usr/lib64/R/library/gamlss/Meta/hsearch.rds
/usr/lib64/R/library/gamlss/Meta/links.rds
/usr/lib64/R/library/gamlss/Meta/nsInfo.rds
/usr/lib64/R/library/gamlss/Meta/package.rds
/usr/lib64/R/library/gamlss/NAMESPACE
/usr/lib64/R/library/gamlss/NEWS.md
/usr/lib64/R/library/gamlss/R/gamlss
/usr/lib64/R/library/gamlss/R/gamlss.rdb
/usr/lib64/R/library/gamlss/R/gamlss.rdx
/usr/lib64/R/library/gamlss/help/AnIndex
/usr/lib64/R/library/gamlss/help/aliases.rds
/usr/lib64/R/library/gamlss/help/gamlss.rdb
/usr/lib64/R/library/gamlss/help/gamlss.rdx
/usr/lib64/R/library/gamlss/help/paths.rds
/usr/lib64/R/library/gamlss/html/00Index.html
/usr/lib64/R/library/gamlss/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/gamlss/libs/gamlss.so
/V4/usr/lib64/R/library/gamlss/libs/gamlss.so
/usr/lib64/R/library/gamlss/libs/gamlss.so
